language: node_js
sudo: true
node_js: stable
script: npm test
env:
  global:
  - CF_APP=watson-test-resources
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=germanatt
  - CF_SPACE=sdks
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    branch: master
    repo: germanattanasio/watson-test-resources
  skip_cleanup: true
notifications:
  email: false
